EDUKREA_TABLES_GROUPED = {
    "Logs and Events": ["mdl_logstore_standard_log", "mdl_task_log", "mdl_config_log", "mdl_block_xp_log", "mdl_log_display", "mdl_event"],
    "Interactive Content": [
        "mdl_hvp_contents_libraries",
        "mdl_hvp_xapi_results",
        "mdl_hvp_libraries_cachedassets",
        "mdl_hvp",
        "mdl_hvp_libraries_languages",
        "mdl_hvp_events",
        "mdl_hvp_tmpfiles",
        "mdl_h5p_library_dependencies",
        "mdl_hvp_libraries_libraries",
        "mdl_hvp_counters",
        "mdl_h5p_libraries",
        "mdl_hvp_libraries",
        "mdl_h5p_contents_libraries",
        "mdl_hvp_libraries_hub_cache",
        "mdl_hvp_content_user_data",
        "mdl_h5p_libraries_cachedassets",
        "mdl_geogebra_attempts",
        "mdl_h5p",
        "mdl_hvp_content_hub_cache",
        "mdl_geogebra",
    ],
    "Assignments and Grades": [
        "mdl_grade_items_history",
        "mdl_grade_grades_history",
        "mdl_grade_grades",
        "mdl_grade_items",
        "mdl_upgrade_log",
        "mdl_role_assignments",
        "mdl_grade_categories_history",
        "mdl_assign_plugin_config",
        "mdl_assign_submission",
        "mdl_grade_categories",
        "mdl_assign",
        "mdl_assign_user_mapping",
        "mdl_role_allow_assign",
        "mdl_assignsubmission_file",
        "mdl_assign_grades",
        "mdl_assignfeedback_editpdf_rot",
    ],
    "Files and Resources": ["mdl_files", "mdl_contentbank_content", "mdl_resource", "mdl_files_reference"],
    "Other": [
        "innodb_index_stats",
        "mdl_block_recentlyaccesseditems",
        "mdl_tiny_autosave",
        "mdl_backup_controllers",
        "mdl_block_recent_activity",
        "mdl_external_functions",
        "help_topic",
        "mdl_grading_areas",
        "mdl_block_instances",
        "mdl_block_xp_filters",
        "innodb_table_stats",
        "mdl_external_services_functions",
        "mdl_enrol",
        "mdl_question_answers",
        "mdl_question",
        "mdl_question_versions",
        "mdl_block_xp",
        "mdl_task_scheduled",
        "mdl_question_bank_entries",
        "help_relation",
        "mdl_sessions",
        "mdl_cache_flags",
        "mdl_qtype_multichoice_options",
        "mdl_qtype_match_subquestions",
        "mdl_question_truefalse",
        "help_category",
        "mdl_question_categories",
        "mdl_block",
        "help_keyword",
        "mdl_qtype_essay_options",
        "mdl_modules",
        "mdl_favourite",
        "mdl_qtype_match_options",
        "mdl_license",
        "mdl_editor_atto_autosave",
        "mdl_filter_active",
        "mdl_block_positions",
        "global_priv",
        "db",
        "mdl_external_services",
        "proxies_priv",
        "mdl_comments",
        "mdl_badge_external_backpack",
        "mdl_format_menutopic",
        "mdl_registration_hubs",
    ],
    "Access and Roles": [
        "mdl_context",
        "mdl_role_capabilities",
        "mdl_capabilities",
        "mdl_role_allow_view",
        "mdl_mnet_remote_rpc",
        "mdl_mnet_remote_service2rpc",
        "mdl_mnet_service2rpc",
        "mdl_mnet_rpc",
        "mdl_role_allow_override",
        "mdl_role_context_levels",
        "mdl_role_allow_switch",
        "mdl_role",
        "mdl_mnet_service",
        "mdl_mnet_application",
        "mdl_mnet_host",
    ],
    "Courses": [
        "mdl_course_modules_completion",
        "mdl_course_modules",
        "mdl_course_modules_viewed",
        "mdl_course_completions",
        "mdl_course_sections",
        "mdl_tool_recyclebin_course",
        "mdl_course_format_options",
        "mdl_course",
        "mdl_course_completion_criteria",
        "mdl_course_categories",
        "mdl_course_completion_aggr_methd",
        "mdl_course_completion_crit_compl",
    ],
    "Analytics": [
        "mdl_analytics_predict_samples",
        "mdl_analytics_indicator_calc",
        "mdl_analytics_predictions",
        "mdl_analytics_used_analysables",
        "mdl_analytics_models",
        "mdl_analytics_prediction_actions",
    ],
    "Messaging": [
        "mdl_notifications",
        "mdl_message_popup_notifications",
        "mdl_message_providers",
        "mdl_message_conversation_members",
        "mdl_message_conversations",
        "mdl_chat_messages",
        "mdl_chat",
        "mdl_message_processors",
        "mdl_messageinbound_handlers",
    ],
    "Users": [
        "mdl_user_preferences",
        "mdl_user_enrolments",
        "mdl_user_lastaccess",
        "mdl_user",
        "mdl_cohort_members",
        "mdl_user_private_key",
        "mdl_cohort",
        "mdl_tool_usertours_steps",
        "mdl_tool_usertours_tours",
    ],
    "Configuration": ["mdl_config_plugins", "mdl_config", "mdl_adminpresets_plug", "mdl_block_xp_config", "mdl_adminpresets_it", "mdl_adminpresets"],
    "Forums": ["mdl_forum_posts", "mdl_forum_discussion_subs", "mdl_forum", "mdl_forum_discussions", "mdl_forum_subscriptions"],
    "Basic Resources": ["mdl_label", "mdl_my_pages", "mdl_lesson_pages", "mdl_page", "mdl_url"],
    "Activities": [
        "mdl_survey_questions",
        "mdl_lesson_branch",
        "mdl_scorm_scoes_value",
        "mdl_lesson_answers",
        "mdl_scorm_attempt",
        "mdl_glossary_formats",
        "mdl_survey",
        "mdl_scorm_element",
        "mdl_scorm_scoes_data",
        "mdl_scorm_scoes",
        "mdl_lesson",
        "mdl_scorm",
    ],
    "Tools and Reports": [
        "mdl_tool_brickfield_checks",
        "mdl_reportbuilder_report",
        "mdl_tool_htmlbootstrapeditor_tpl",
        "mdl_tool_dataprivacy_request",
    ],
    "Tags": ["mdl_tag_area", "mdl_tag_instance", "mdl_tag", "mdl_tag_coll"],
    "Repositories": ["mdl_repository_instances", "mdl_repository"],
    "Quizzes": ["mdl_quiz_reports"],
    "Scales": ["mdl_scale"],
}

MOODLE_TABLES_GROUPED = {
    "Analytics": [
        "mdlvf_analytics_indicator_calc",
        "mdlvf_analytics_models",
        "mdlvf_analytics_predict_samples",
        "mdlvf_analytics_prediction_actions",
        "mdlvf_analytics_predictions",
        "mdlvf_analytics_used_analysables",
        "mdlvf_analytics_used_files",
    ],
    "Assignments": [
        "mdlvf_assign",
        "mdlvf_assign_grades",
        "mdlvf_assign_plugin_config",
        "mdlvf_assign_submission",
        "mdlvf_assign_user_flags",
        "mdlvf_assign_user_mapping",
        "mdlvf_assignfeedback_comments",
        "mdlvf_assignfeedback_editpdf_annot",
        "mdlvf_assignfeedback_editpdf_cmnt",
        "mdlvf_assignfeedback_editpdf_queue",
        "mdlvf_assignfeedback_editpdf_quick",
        "mdlvf_assignfeedback_editpdf_rot",
        "mdlvf_assignsubmission_file",
        "mdlvf_assignsubmission_onlinetext",
    ],
    "Backup": [
        "mdlvf_backup_controllers",
        "mdlvf_backup_logs",
    ],
    "Badges": [
        "mdlvf_badge_external_backpack",
    ],
    "Blocks": [
        "mdlvf_block",
        "mdlvf_block_instances",
        "mdlvf_block_positions",
        "mdlvf_block_recent_activity",
        "mdlvf_block_recentlyaccesseditems",
    ],
    "Book": [
        "mdlvf_book",
        "mdlvf_book_chapters",
    ],
    "Chat": [
        "mdlvf_chat",
        "mdlvf_chat_messages",
    ],
    "Choice": [
        "mdlvf_choice",
        "mdlvf_choice_answers",
        "mdlvf_choice_options",
    ],
    "Comments": [
        "mdlvf_comments",
    ],
    "Content": [
        "mdlvf_bootstrapelements",
        "mdlvf_files",
        "mdlvf_folder",
        "mdlvf_glossary",
        "mdlvf_glossary_formats",
        "mdlvf_label",
        "mdlvf_url",
    ],
    "Course": [
        "mdlvf_course",
        "mdlvf_course_categories",
        "mdlvf_course_completion_defaults",
        "mdlvf_course_completions",
        "mdlvf_course_format_options",
        "mdlvf_course_modules",
        "mdlvf_course_modules_completion",
        "mdlvf_course_sections",
        "mdlvf_event",
        "mdlvf_grade_categories",
        "mdlvf_grade_categories_history",
        "mdlvf_grade_grades",
        "mdlvf_grade_grades_history",
        "mdlvf_grade_items",
        "mdlvf_grade_items_history",
        "mdlvf_grade_settings",
        "mdlvf_resource",
        "mdlvf_tool_dataprivacy_request",
        "mdlvf_tool_recyclebin_course",
        "mdlvf_tool_usertours_steps",
        "mdlvf_tool_usertours_tours",
    ],
    "Course Formats": [
        "mdlvf_format_grid_icon",
        "mdlvf_format_grid_summary",
        "mdlvf_modules",
    ],
    "Enrollment": [
        "mdlvf_enrol",
        "mdlvf_user_enrolments",
    ],
    "External Services": [
        "mdlvf_external_functions",
        "mdlvf_external_services",
        "mdlvf_external_services_functions",
        "mdlvf_external_services_users",
        "mdlvf_external_tokens",
        "mdlvf_repository",
        "mdlvf_repository_instances",
    ],
    "Feedback": [
        "mdlvf_feedback",
        "mdlvf_feedback_completed",
        "mdlvf_feedback_item",
        "mdlvf_feedback_value",
    ],
    "Filters": [
        "mdlvf_filter_active",
    ],
    "Forum": [
        "mdlvf_forum",
        "mdlvf_forum_discussion_subs",
        "mdlvf_forum_discussions",
        "mdlvf_forum_grades",
        "mdlvf_forum_posts",
        "mdlvf_forum_subscriptions",
    ],
    "Grading": [
        "mdlvf_grading_areas",
        "mdlvf_grading_definitions",
        "mdlvf_grading_instances",
        "mdlvf_gradingform_rubric_criteria",
        "mdlvf_gradingform_rubric_fillings",
        "mdlvf_gradingform_rubric_levels",
        "mdlvf_rating",
        "mdlvf_scale",
    ],
    "h5": [
        "mdlvf_h5p_libraries",
        "mdlvf_h5p_library_dependencies",
        "mdlvf_hvp",
        "mdlvf_hvp_content_hub_cache",
        "mdlvf_hvp_content_user_data",
        "mdlvf_hvp_contents_libraries",
        "mdlvf_hvp_counters",
        "mdlvf_hvp_events",
        "mdlvf_hvp_libraries",
        "mdlvf_hvp_libraries_cachedassets",
        "mdlvf_hvp_libraries_hub_cache",
        "mdlvf_hvp_libraries_languages",
        "mdlvf_hvp_libraries_libraries",
        "mdlvf_hvp_tmpfiles",
        "mdlvf_hvp_xapi_results",
    ],
    "Lesson": [
        "mdlvf_lesson",
    ],
    "License": [
        "mdlvf_license",
    ],
    "Log": [
        "mdlvf_log_display",
        "mdlvf_logstore_standard_log",
        "mdlvf_upgrade_log",
    ],
    "LTI": [
        "mdlvf_lti",
        "mdlvf_lti_submission",
    ],
    "Messages": [
        "mdlvf_message",
        "mdlvf_message_contact_requests",
        "mdlvf_message_contacts",
        "mdlvf_message_conversation_actions",
        "mdlvf_message_conversation_members",
        "mdlvf_message_conversations",
        "mdlvf_message_popup",
        "mdlvf_message_popup_notifications",
        "mdlvf_message_processors",
        "mdlvf_message_providers",
        "mdlvf_message_read",
        "mdlvf_message_user_actions",
        "mdlvf_message_users_blocked",
        "mdlvf_messageinbound_handlers",
        "mdlvf_messages",
    ],
    "Mnet": [
        "mdlvf_mnet_application",
        "mdlvf_mnet_host",
        "mdlvf_mnet_remote_rpc",
        "mdlvf_mnet_remote_service2rpc",
        "mdlvf_mnet_rpc",
        "mdlvf_mnet_service",
        "mdlvf_mnet_service2rpc",
    ],
    "Notifications": [
        "mdlvf_notifications",
        "mdlvf_registration_hubs",
    ],
    "Page": [
        "mdlvf_page",
    ],
    "Questions": [
        "mdlvf_qtype_ddimageortext",
        "mdlvf_qtype_ddimageortext_drags",
        "mdlvf_qtype_ddimageortext_drops",
        "mdlvf_qtype_ddmarker",
        "mdlvf_qtype_ddmarker_drags",
        "mdlvf_qtype_essay_options",
        "mdlvf_qtype_match_options",
        "mdlvf_qtype_match_subquestions",
        "mdlvf_qtype_multichoice_options",
        "mdlvf_qtype_shortanswer_options",
        "mdlvf_question",
        "mdlvf_question_answers",
        "mdlvf_question_attempt_step_data",
        "mdlvf_question_attempt_steps",
        "mdlvf_question_attempts",
        "mdlvf_question_categories",
        "mdlvf_question_ddwtos",
        "mdlvf_question_gapselect",
        "mdlvf_question_hints",
        "mdlvf_question_numerical",
        "mdlvf_question_numerical_options",
        "mdlvf_question_truefalse",
        "mdlvf_question_usages",
    ],
    "Quiz": [
        "mdlvf_quiz",
        "mdlvf_quiz_attempts",
        "mdlvf_quiz_feedback",
        "mdlvf_quiz_grades",
        "mdlvf_quiz_reports",
        "mdlvf_quiz_sections",
        "mdlvf_quiz_slots",
    ],
    "Survey": [
        "mdlvf_survey",
        "mdlvf_survey_questions",
    ],
    "System": [
        "mdlvf_cache_flags",
        "mdlvf_capabilities",
        "mdlvf_config",
        "mdlvf_config_log",
        "mdlvf_config_plugins",
        "mdlvf_context",
    ],
    "Tags": [
        "mdlvf_tag",
        "mdlvf_tag_area",
        "mdlvf_tag_coll",
        "mdlvf_tag_instance",
    ],
    "Task": [
        "mdlvf_task_adhoc",
        "mdlvf_task_log",
        "mdlvf_task_scheduled",
    ],
    "Users": [
        "mdlvf_cohort",
        "mdlvf_cohort_members",
        "mdlvf_favourite",
        "mdlvf_groups",
        "mdlvf_my_pages",
        "mdlvf_role",
        "mdlvf_role_allow_assign",
        "mdlvf_role_allow_override",
        "mdlvf_role_allow_switch",
        "mdlvf_role_allow_view",
        "mdlvf_role_assignments",
        "mdlvf_role_capabilities",
        "mdlvf_role_context_levels",
        "mdlvf_sessions",
        "mdlvf_user",
        "mdlvf_user_devices",
        "mdlvf_user_info_category",
        "mdlvf_user_info_data",
        "mdlvf_user_info_field",
        "mdlvf_user_lastaccess",
        "mdlvf_user_preferences",
        "mdlvf_user_private_key",
    ],
    "Workshop": [
        "mdlvf_workshop",
    ],
}
